---
name: Airflow sync
on:
  schedule:
    - cron: '16 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: apache/airflow
          target_repository: turbaszek/airflow
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
