---
name: KEDA sync
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  sync:
    name: apache/airflow
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.SYNC_KEY }}
          upstream_repository: kedacore/keda
          target_repository: turbaszek/keda
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
